project_id = "onfcgdhyaqoqxhroorjc"

[functions.check-subscription]
verify_jwt = true

[functions.premium-chatbot]
verify_jwt = true

[functions.notify-payment]
verify_jwt = true

[functions.setup-admin]
verify_jwt = false
